;*  SMALL-C HEADER FILE

 ORG $800

fclose EQU $104
fopen EQU $108
getc EQU $10C
getchar EQU $110
gets EQU $114
putc EQU $118
putchar EQU $11C
puts EQU $120
RTSC EQU $124
isalpha EQU $128
isdigit EQU $12C
isalnum EQU $130
islower EQU $134
isupper EQU $138
isspace EQU $13C
toupper EQU $140
tolower EQU $144
strclr EQU $148
strlen EQU $14C
strcpy EQU $150
strcat EQU $154
strcmp EQU $158
exit   EQU $15C
EOF EQU -1
