VM = ./scvm

all: unicc unias UNICC.CMD UNIAS.CMD

CFLAGS = -O2

scvm: scvm.o
	$(CC) -o $@ $^

SMALLCX.CMD: scvm NATIVE/SMALLCX.C
	$(VM) BOOTSTRAP/SMALLC.CMD -o SMALLCX.ASM NATIVE/SMALLCX.C
	$(VM) BOOTSTRAP/AS03.CMD -o SMALLCX.CMD SMALLCX.ASM

AS03X.CMD: scvm AS03/AS03.C SMALLCX.CMD
	cd AS03 && ../$(VM) ../SMALLCX.CMD -o ../AS03X.ASM AS03.C
	$(VM) BOOTSTRAP/AS03.CMD -o AS03X.CMD AS03X.ASM

SMALLC.CMD: scvm NATIVE/SMALLCX.C SMALLCX.CMD AS03X.CMD
	$(VM) SMALLCX.CMD -o SMALLC.ASM NATIVE/SMALLCX.C
	$(VM) AS03X.CMD -o SMALLC.CMD SMALLC.ASM

AS03.CMD: scvm AS03/AS03.C AS03X.CMD SMALLC.CMD
	cd AS03 && ../$(VM) ../SMALLC.CMD -o ../AS03.ASM AS03.C
	$(VM) AS03X.CMD -o AS03.CMD AS03.ASM

unicc: scvm.c unicc.h
	$(CC) -o $@ scvm.c -DAPP=\"unicc.h\" -Wall $(CFLAGS)

unicc.h: SMALLC.CMD
	hexdump -v -e '"\t" 16/1 "0x%02x, " "\n"' $^ | sed 's/0x  ,//g' > $@

unias: scvm.c unias.h
	$(CC) -o $@ scvm.c -DAPP=\"unias.h\" -Wall $(CFLAGS)

unias.h: AS03.CMD
	hexdump -v -e '"\t" 16/1 "0x%02x, " "\n"' $^ | sed 's/0x  ,//g' > $@

UNIAS.CMD: AS03.CMD ZCODE.ROM
	cp -f AS03.CMD UNIAS.CMD

UNICC.CMD: SMALLC.CMD ZCODE.ROM
	$(VM) SMALLC.CMD -o UNICC.ASM NATIVE/SMALLC.C
	$(VM) AS03.CMD UNICC.ASM

ZCODE.ROM: AS03.CMD ZCODE.ASM
	$(VM) AS03.CMD -l ZCODE.LST -o ZCODE.CMD ZCODE.ASM
	mv -f ZCODE.CMD ZCODE.ROM

clean:
	rm -f scvm *.o out.sym AS03X.CMD AS03X.ASM SMALLCX.CMD SMALLCX.ASM AS03.CMD AS03.ASM SMALLC.CMD SMALLC.ASM
	rm -f unicc unicc.h
	rm -f unias unias.h
	rm -f UNICC.ASM UNIAS.CMD UNICC.CMD UNIAS.CMD ZCODE.ROM ZCODE.LST
